/**
 * Real QA Worker — spawned by AcpController as a child process.
 *
 * This script simulates meaningful work (file generation), creates real
 * artifacts, and communicates back to ClientNode via CLI → IPC.
 *
 * Communication channels:
 *   stdin/stdout — ACP protocol (JSON-RPC over ndjson)
 *   shell exec   — `dispatch worker progress/complete/fail` CLI commands
 *
 * Since the CLI is not fully wired yet, this worker uses a fallback:
 * it writes progress/completion via direct HTTP to the server, BUT
 * constructs real artifact files on disk (zip + result.json).
 */

import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';

const SERVER_URL = process.env['SERVER_URL'] ?? 'http://localhost:9800';
const TASK_ID = process.env['TASK_ID'] ?? '';
const AGENT_ID = process.env['AGENT_ID'] ?? '';
const CLIENT_ID = process.env['CLIENT_ID'] ?? '';
const WORK_DIR = process.env['WORK_DIR'] ?? process.cwd();

function log(msg: string): void {
  const ts = new Date().toISOString().slice(11, 19);
  process.stderr.write(`[${ts}] [worker:${AGENT_ID}] ${msg}\n`);
}

async function reportProgress(progress: number, message: string): Promise<void> {
  try {
    await fetch(`${SERVER_URL}/api/v1/tasks/${TASK_ID}/progress`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ clientId: CLIENT_ID, agentId: AGENT_ID, progress, message }),
    });
    log(`Progress: ${progress}% — ${message}`);
  } catch (e: unknown) {
    log(`Progress report failed: ${e instanceof Error ? e.message : String(e)}`);
  }
}

async function doWork(): Promise<void> {
  const outputDir = path.join(WORK_DIR, 'output');
  fs.mkdirSync(outputDir, { recursive: true });

  await reportProgress(10, 'Initializing workspace...');
  await sleep(1500);

  await reportProgress(30, 'Analyzing task requirements...');
  const analysisFile = path.join(outputDir, 'analysis.md');
  fs.writeFileSync(analysisFile, `# Task Analysis\n\n- Task ID: ${TASK_ID}\n- Agent: ${AGENT_ID}\n- Timestamp: ${new Date().toISOString()}\n\n## Findings\n\nTask analyzed and processed successfully.\n`);
  await sleep(2000);

  await reportProgress(60, 'Generating output...');
  const resultFile = path.join(outputDir, 'output.txt');
  fs.writeFileSync(resultFile, `Output generated by worker ${AGENT_ID}\nTask: ${TASK_ID}\nCompleted at: ${new Date().toISOString()}\n`);
  await sleep(2000);

  await reportProgress(85, 'Packaging artifacts...');

  const zipPath = path.join(outputDir, 'artifact.zip');
  try {
    execSync(`cd "${outputDir}" && zip -r artifact.zip analysis.md output.txt`, { stdio: 'pipe' });
  } catch {
    const zipBuf = createMinimalZip([
      { name: 'analysis.md', content: fs.readFileSync(analysisFile) },
      { name: 'output.txt', content: fs.readFileSync(resultFile) },
    ]);
    fs.writeFileSync(zipPath, zipBuf);
  }

  const resultJsonPath = path.join(outputDir, 'result.json');
  const resultJson = {
    taskId: TASK_ID,
    success: true,
    summary: `Task completed by ${AGENT_ID}. Generated analysis and output files.`,
    outputs: [
      { name: 'analysis', type: 'report', path: 'analysis.md', description: 'Task analysis report' },
      { name: 'output', type: 'file', path: 'output.txt', description: 'Generated output' },
    ],
    metrics: { durationSeconds: 8 },
  };
  fs.writeFileSync(resultJsonPath, JSON.stringify(resultJson, null, 2));
  await sleep(1000);

  await reportProgress(95, 'Uploading artifacts...');

  const zipBuf = fs.readFileSync(zipPath);
  const resultBuf = fs.readFileSync(resultJsonPath);

  const boundary = `----FormBoundary${Date.now()}`;
  const parts: Buffer[] = [];
  parts.push(Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="zip"; filename="artifact.zip"\r\nContent-Type: application/zip\r\n\r\n`));
  parts.push(zipBuf);
  parts.push(Buffer.from(`\r\n--${boundary}\r\nContent-Disposition: form-data; name="result"; filename="result.json"\r\nContent-Type: application/json\r\n\r\n`));
  parts.push(resultBuf);
  parts.push(Buffer.from(`\r\n--${boundary}--\r\n`));

  const body = Buffer.concat(parts);
  const res = await fetch(`${SERVER_URL}/api/v1/tasks/${TASK_ID}/complete`, {
    method: 'POST',
    headers: { 'Content-Type': `multipart/form-data; boundary=${boundary}` },
    body,
  });

  if (res.ok) {
    log('Task completed successfully!');
  } else {
    const text = await res.text();
    log(`Completion failed: ${res.status} ${text}`);
  }
}

function createMinimalZip(files: Array<{ name: string; content: Buffer }>): Buffer {
  const localHeaders: Buffer[] = [];
  const centralHeaders: Buffer[] = [];
  let offset = 0;

  for (const file of files) {
    const nameBytes = Buffer.from(file.name, 'utf-8');
    const localHeader = Buffer.alloc(30 + nameBytes.length);
    localHeader.writeUInt32LE(0x04034b50, 0);
    localHeader.writeUInt16LE(20, 4);
    localHeader.writeUInt32LE(file.content.length, 18);
    localHeader.writeUInt32LE(file.content.length, 22);
    localHeader.writeUInt16LE(nameBytes.length, 26);
    nameBytes.copy(localHeader, 30);

    localHeaders.push(localHeader, file.content);

    const centralEntry = Buffer.alloc(46 + nameBytes.length);
    centralEntry.writeUInt32LE(0x02014b50, 0);
    centralEntry.writeUInt16LE(20, 4);
    centralEntry.writeUInt16LE(20, 6);
    centralEntry.writeUInt32LE(file.content.length, 20);
    centralEntry.writeUInt32LE(file.content.length, 24);
    centralEntry.writeUInt16LE(nameBytes.length, 28);
    centralEntry.writeUInt32LE(offset, 42);
    nameBytes.copy(centralEntry, 46);

    centralHeaders.push(centralEntry);
    offset += localHeader.length + file.content.length;
  }

  const centralDirOffset = offset;
  const centralDirSize = centralHeaders.reduce((s, b) => s + b.length, 0);

  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);
  eocd.writeUInt16LE(files.length, 8);
  eocd.writeUInt16LE(files.length, 10);
  eocd.writeUInt32LE(centralDirSize, 12);
  eocd.writeUInt32LE(centralDirOffset, 16);

  return Buffer.concat([...localHeaders, ...centralHeaders, eocd]);
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

if (!TASK_ID || !AGENT_ID || !CLIENT_ID) {
  log('Missing required env: TASK_ID, AGENT_ID, CLIENT_ID');
  process.exit(1);
}

log(`Starting work on task ${TASK_ID}`);
doWork()
  .then(() => {
    log('Worker finished');
    process.exit(0);
  })
  .catch((err) => {
    log(`Worker crashed: ${err}`);
    process.exit(1);
  });
